import Head from "next/head";
import FilterComponent from "../components/FilterComponent";
import TodoList from "../components/TodoList";
import todos from "../utils/todos";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Todoie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="vh-100">
        <div className="container py-5 h-100">
          <div className="row d-flex justify-content-center align-items-center h-100">
            <div className="col">
              <div className="card" id="list1">
                <div className="card-body py-4 px-4 px-md-5">
                  <p className="h1 text-center mt-3 mb-4 pb-3 text-primary">
                    <i className="bi-check-square me-1"></i>
                    <u>My Todo-s</u>
                  </p>
                  <div className="pb-2">
                    <div className="card">
                      <div className="card-body">
                        <div className="d-flex flex-row align-items-center">
                          <input
                            type="text"
                            className="form-control form-control-lg"
                            id="exampleFormControlInput1"
                            placeholder="Add new..."
                          />
                          <a href="#!" title="Set due date">
                            <i className="bi-calendar  me-3"></i>
                          </a>
                          <div>
                            <button type="button" className="btn btn-primary">
                              Add
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <hr className="my-4" />
                  <FilterComponent />
                  <TodoList todoslist={ todos } />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
