import Head from "next/head";
import { useState } from "react";
import FilterComponent from "../components/FilterComponent";
import TodoList from "../components/TodoList";
import TodoStatus from "../utils/helper";
import todos from "../utils/todos";

export default function Home() {
  const [todosList, setTodos] = useState(todos);
  const [todo, setTodo] = useState("");
  const handleChange = (e) => {
    setTodo(e.target.value);
  };

  const handleAddTodo = () => {
    let todayDate = new Date().toLocaleDateString();
    setTodos([
      ...todosList,
      {
        id: Math.floor(Math.random() * 100),
        title: todo,
        date: todayDate,
        status: TodoStatus.Active,
      },
    ]);
    setTodo("");
  };
  return (
    <div>
      <Head>
        <title>Todoie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="vh-100">
        <div className="container py-5 h-100">
          <div className="row d-flex justify-content-center align-items-center h-100">
            <div className="col">
              <div className="card" id="list1">
                <div className="card-body py-4 px-4 px-md-5">
                  <p className="h1 text-center mt-3 mb-4 pb-3 text-primary">
                    <i className="bi-check-square me-1"></i>
                    <u>My Todo-s</u>
                  </p>
                  <div className="pb-2">
                    <div className="card">
                      <div className="card-body">
                        <div className="d-flex flex-row align-items-center">
                          <input
                            type="text"
                            required={true}
                            className="form-control form-control-lg"
                            id="exampleFormControlInput1"
                            placeholder="Add new..."
                            value={todo}
                            onChange={handleChange}
                            minLength="6"
                            maxLength="60"
                          />
                          <a href="#!" title="Set due date">
                            <i className="bi-calendar  me-3"></i>
                          </a>
                          <div>
                            <button
                              type="button"
                              className="btn btn-primary"
                              //only when user submit a todo string then add todo
                              onClick={() => {
                                todo && handleAddTodo();
                              }}
                            >
                              Add
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <hr className="my-4" />
                  <FilterComponent />
                  <TodoList todoslist={todosList} />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
